---
abstract: 'safer monkey-patching; Ruby-2.0-style refinements for Perl'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Refinements
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Refinements:
    file: lib/Refinements.pm
    version: 0.001
  Refinements::Package:
    file: lib/Refinements/Package.pm
    version: 0.001
requires:
  Exporter::Tiny: 0
  Method::Lexical: 0
  Module::Runtime: 0
  perl: 5.010
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Refinements/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Refinements
  homepage: https://metacpan.org/release/Refinements
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-refinements
version: 0.001
